# Generated by Django 5.2.3 on 2025-06-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
