# Generated by Django 5.2.3 on 2025-06-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
