# Generated by Django 5.2 on 2025-06-14 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobcard_business', '0004_delete_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('employer_id', models.CharField(max_length=50)),
                ('jsj_business_id', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('workplace', models.CharField(max_length=100)),
                ('staff_email', models.EmailField(max_length=254)),
                ('application_end_date', models.DateField()),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=20)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requirements', models.TextField()),
                ('about_company', models.TextField()),
                ('description', models.TextField()),
                ('languages', models.JSONField(blank=True, default=list)),
                ('area_of_work', models.JSONField(blank=True, default=list)),
                ('industry', models.CharField(max_length=100)),
                ('number_of_posts', models.PositiveIntegerField()),
                ('education_levels', models.JSONField(blank=True, default=list)),
                ('specialisations', models.JSONField(blank=True, default=list)),
                ('key_skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('member_card', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('resume', models.TextField()),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('application_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobcard_business.job')),
            ],
        ),
    ]
