# Generated by Django 5.2 on 2025-06-14 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='jsj_business_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='staff_email',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='application_number',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='candidate_email',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='candidate_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='location',
        ),
        migrations.AddField(
            model_name='job',
            name='business_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='institute_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Institute ID'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('selected', 'Selected')], default='applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='member_card',
            field=models.BigIntegerField(verbose_name='Member Card Number'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.TextField(max_length=255),
        ),
    ]
