# Generated by Django 5.2.3 on 2025-06-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0006_remove_job_employer_id_remove_job_jsj_business_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='business_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
