# Generated by Django 5.2 on 2025-06-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0006_remove_job_employer_id_remove_job_jsj_business_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='referral',
            field=models.BigIntegerField(blank=True, help_text='ID of the person who referred this applicant', null=True, verbose_name='Referral id'),
        ),
    ]
