# Generated by Django 5.2.3 on 2025-06-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0007_job_business_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='mitra_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
