# Generated by Django 5.2 on 2025-06-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0007_jobapplication_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='referral',
            field=models.IntegerField(blank=True, help_text='ID of the employee who submitted the application', null=True),
        ),
    ]
