# Generated by Django 5.1.7 on 2025-06-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0008_jobapplication_mitra_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='business_address',
        ),
        migrations.AddField(
            model_name='job',
            name='job_mitra_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
