# Generated by Django 5.2 on 2025-06-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0008_alter_jobapplication_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='about_company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='application_end_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='area_of_work',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='education_levels',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
        migrations.RemoveField(
            model_name='job',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='key_skills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='min_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='number_of_posts',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='job',
            name='specialisations',
        ),
        migrations.RemoveField(
            model_name='job',
            name='video',
        ),
        migrations.RemoveField(
            model_name='job',
            name='workplace',
        ),
    ]
