# Generated by Django 5.1.7 on 2025-06-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0009_remove_job_business_address_job_job_mitra_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
