# Generated by Django 5.2 on 2025-06-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0009_remove_job_about_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='education_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('0-1 Years', '0-1 Years'), ('1-3 Years', '1-3 Years'), ('3-5 Years', '3-5 Years'), ('5+ Years', '5+ Years')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('IT', 'IT'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Retail', 'Retail'), ('Construction', 'Construction'), ('Manufacturing', 'Manufacturing'), ('Hospitality', 'Hospitality')], default='IT', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='key_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='number_of_posts',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='pay_rate',
            field=models.CharField(choices=[('per year', 'per year'), ('per month', 'per month'), ('per week', 'per week'), ('per day', 'per day'), ('per hour', 'per hour')], default='per year', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='recruitment_timeline',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('1 Month', '1 Month'), ('Flexible', 'Flexible')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='specialisations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='workplace',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
