# Generated by Django 5.2 on 2025-06-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0010_job_application_end_date_job_area_job_company_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pay_rate',
            field=models.CharField(max_length=20),
        ),
    ]
