# Generated by Django 5.2 on 2025-07-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0011_alter_job_pay_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video link', max_length=255, null=True),
        ),
    ]
