# Generated by Django 5.2 on 2025-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0012_job_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.BigIntegerField(verbose_name='Member Card Number')),
                ('happiness_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Happiness Rating')),
                ('has_issues', models.BooleanField(verbose_name='Facing any issues?')),
                ('issues_detail', models.TextField(blank=True, null=True, verbose_name='Issue Details')),
                ('liked_most', models.TextField(blank=True, null=True, verbose_name='What do you like most?')),
                ('suggestions', models.TextField(blank=True, null=True, verbose_name='Suggestions for improvement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
