# Generated by Django 5.2 on 2025-08-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0013_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='business_id',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Business ID'),
        ),
    ]
