# Generated by Django 5.2 on 2025-08-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0014_feedback_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='business_id',
            field=models.IntegerField(blank=True, max_length=6, null=True, verbose_name='Business ID'),
        ),
    ]
