# Generated by Django 5.2 on 2025-08-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0016_alter_feedback_business_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255, verbose_name='Candidate Name')),
                ('card_number', models.BigIntegerField(verbose_name='Card Number')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('employee_id', models.CharField(max_length=100, verbose_name='Employee ID')),
                ('feedback_questions', models.JSONField(default=dict, help_text="Store feedback questions and answers as JSON, e.g., {'Question 1': 'Answer'}")),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Additional Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.IntegerField(verbose_name='Business Id')),
            ],
        ),
    ]
