# Generated by Django 5.2 on 2025-08-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0017_hrfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrfeedback',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='hrfeedback',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='hrfeedback',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='hrfeedback',
            name='feedback_questions',
        ),
        migrations.RemoveField(
            model_name='hrfeedback',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='hrfeedback',
            name='requested_by',
        ),
        migrations.AddField(
            model_name='hrfeedback',
            name='feedbacks',
            field=models.JSONField(default=list, help_text="Store multiple company feedbacks as a list of dicts. \n    Each dict can include company info, job info, feedback, comments, and business ID, e.g.:\n\n    [\n        {\n            'company_name': 'ABC',\n            'job_title': 'Developer',\n            'employee_id': 'E123',\n            'feedback_questions': {'Question 1': 'Answer'},\n            'comments': 'Good candidate',\n            'business_id': 101\n        },\n   \n    ]\n    "),
        ),
        migrations.AlterField(
            model_name='hrfeedback',
            name='card_number',
            field=models.BigIntegerField(unique=True, verbose_name='Card Number'),
        ),
    ]
