# Generated by Django 5.2 on 2025-08-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0018_remove_hrfeedback_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrfeedback',
            name='feedbacks',
            field=models.JSONField(default=list, help_text="Store multiple company feedbacks as a list of dicts. \n    Each dict can include company info, job info, feedback, comments, and business ID, e.g.:\n\n    [\n        {\n            'company_name': 'ABC',\n            'job_title': 'Developer',\n            'employee_id': 'E123',\n            'feedback_questions': {'Question 1': 'Answer'},\n            'comments': 'Good candidate',\n            'business_id': 101365\n        },\n   \n    ]\n    "),
        ),
    ]
