# Generated by Django 5.2 on 2025-08-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0019_alter_hrfeedback_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrfeedback',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Comments'),
        ),
        migrations.AddField(
            model_name='hrfeedback',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AddField(
            model_name='hrfeedback',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Department / Role'),
        ),
        migrations.AddField(
            model_name='hrfeedback',
            name='last_working_day',
            field=models.DateField(blank=True, null=True, verbose_name='Last Working Day'),
        ),
    ]
