# Generated by Django 5.2 on 2025-08-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0020_hrfeedback_comments_hrfeedback_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrfeedback',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee ID'),
        ),
        migrations.AddField(
            model_name='hrfeedback',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title'),
        ),
    ]
