# Generated by Django 5.2 on 2025-08-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_business', '0023_hrfeedback_comments_hrfeedback_date_of_joining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrfeedback',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='hrfeedback',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='hrfeedback',
            name='department',
        ),
        migrations.RemoveField(
            model_name='hrfeedback',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='hrfeedback',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='hrfeedback',
            name='last_working_day',
        ),
    ]
