# Generated by Django 5.2 on 2025-06-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_staff', '0003_delete_mbrdocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
