# Generated by Django 5.2.3 on 2025-06-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_staff', '0004_alter_job_image_alter_job_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
