# Generated by Django 5.2.3 on 2025-06-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_staff', '0005_jobapplication_application_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='member_id',
            new_name='member_card',
        ),
        migrations.AddField(
            model_name='job',
            name='jsj_business_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
