# Generated by Django 5.2.3 on 2025-06-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_staff', '0006_rename_member_id_jobapplication_member_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.TextField(),
        ),
    ]
