# Generated by Django 5.2 on 2025-06-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_staff', '0007_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
