# Generated by Django 5.2.4 on 2025-07-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobcard_staff', '0008_remove_jobapplication_job_delete_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(choices=[('Business', 'Business'), ('Member', 'Member'), ('Institute', 'Institute')], max_length=10)),
                ('status', models.CharField(choices=[('Hot', 'Hot'), ('Cold', 'Cold'), ('Neutral', 'Neutral')], default='Neutral', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
