# Generated by Django 5.2.4 on 2025-07-17 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_staff', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='jobcard_staff.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'user')},
            },
        ),
    ]
