# Generated by Django 5.2.4 on 2025-07-17 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_staff', '0011_emailcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=160)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobcard_staff.campaign')),
            ],
        ),
    ]
