# Generated by Django 5.2.4 on 2025-07-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_staff', '0012_smscontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('message_parameters', models.JSONField()),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobcard_staff.campaign')),
            ],
        ),
    ]
