# Generated by Django 5.2.1 on 2025-05-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_certificate', models.TextField(blank=True, null=True)),
                ('twelfth_certificate', models.TextField(blank=True, null=True)),
                ('graduation_certificate', models.TextField(blank=True, null=True)),
                ('pg_certificate', models.TextField(blank=True, null=True)),
                ('graduation_marksheet', models.TextField(blank=True, null=True)),
                ('technical_certification', models.TextField(blank=True, null=True)),
                ('language_certification', models.TextField(blank=True, null=True)),
                ('soft_skill_certification', models.TextField(blank=True, null=True)),
                ('aadhaar_card', models.TextField(blank=True, null=True)),
                ('pan_card', models.TextField(blank=True, null=True)),
                ('passport', models.TextField(blank=True, null=True)),
                ('driving_license', models.TextField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
                ('github_url', models.URLField(blank=True, max_length=255, null=True)),
                ('portfolio_website', models.URLField(blank=True, max_length=255, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('offer_letter', models.TextField(blank=True, null=True)),
                ('personal_statement', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
