# Generated by Django 5.2 on 2025-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MbrDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.BigIntegerField(blank=True, null=True, verbose_name=' member cardnumber')),
                ('TenthCertificate', models.TextField(blank=True, null=True)),
                ('TwelfthCertificate', models.TextField(blank=True, null=True)),
                ('GraduationCertificate', models.TextField(blank=True, null=True)),
                ('GraduationMarksheet', models.TextField(blank=True, null=True)),
                ('PgCertificate', models.TextField(blank=True, null=True)),
                ('UpskillCertificate', models.TextField(blank=True, null=True)),
                ('ItiCertificate', models.TextField(blank=True, null=True)),
                ('ItiMarksheet', models.TextField(blank=True, null=True)),
                ('DiplomaCertificate', models.TextField(blank=True, null=True)),
                ('DiplomaMarksheet', models.TextField(blank=True, null=True)),
                ('CoverLetter', models.TextField(blank=True, null=True)),
                ('Resume', models.TextField(blank=True, null=True)),
                ('AdharcardVoterid', models.TextField(blank=True, null=True)),
                ('LinkedinUrl', models.URLField(blank=True, null=True)),
                ('GithubUrl', models.URLField(blank=True, null=True)),
                ('OtherLink', models.URLField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
