# Generated by Django 5.2.1 on 2025-05-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='member',
            field=models.IntegerField(blank=True, null=True, verbose_name=' member cardnumber'),
        ),
    ]
