# Generated by Django 5.2 on 2025-06-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbrdocuments',
            name='card_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Member Card Number'),
        ),
    ]
