# Generated by Django 5.2.1 on 2025-06-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0002_document_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='member',
            field=models.BigIntegerField(blank=True, null=True, verbose_name=' member cardnumber'),
        ),
    ]
