# Generated by Django 5.2.3 on 2025-06-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0002_alter_mbrdocuments_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('employer_id', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('workplace', models.CharField(max_length=100)),
                ('staff_email', models.EmailField(max_length=254)),
                ('application_end_date', models.DateField()),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requirements', models.TextField()),
                ('about_company', models.TextField()),
                ('description', models.TextField()),
                ('languages', models.JSONField(blank=True, default=list)),
                ('area_of_work', models.JSONField(blank=True, default=list)),
                ('industry', models.CharField(max_length=100)),
                ('number_of_posts', models.PositiveIntegerField()),
                ('education_levels', models.JSONField(blank=True, default=list)),
                ('specialisations', models.JSONField(blank=True, default=list)),
                ('key_skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='job_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='job_videos/')),
            ],
        ),
    ]
