# Generated by Django 5.2.1 on 2025-06-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0004_candidate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='RegisterCandidate',
        ),
    ]
