# Generated by Django 5.2.3 on 2025-06-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0004_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
