# Generated by Django 5.2.4 on 2025-07-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0005_delete_jobapplication_delete_jobpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
