# Generated by Django 5.2 on 2025-07-21 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0005_delete_jobapplication_delete_jobpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(choices=[('TenthCertificate', '10th Certificate'), ('TwelfthCertificate', '12th Certificate'), ('GraduationCertificate', 'Graduation Certificate'), ('GraduationMarksheet', 'Graduation Marksheet'), ('PgCertificate', 'PG Certificate'), ('UpskillCertificate', 'Upskill Certificate'), ('ItiCertificate', 'ITI Certificate'), ('ItiMarksheet', 'ITI Marksheet'), ('DiplomaCertificate', 'Diploma Certificate'), ('DiplomaMarksheet', 'Diploma Marksheet'), ('CoverLetter', 'Cover Letter'), ('Resume', 'Resume'), ('AdharcardVoterid', 'Aadhar/Voter ID'), ('LinkedinUrl', 'LinkedIn URL'), ('GithubUrl', 'GitHub URL'), ('OtherLink', 'Other Link')], max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobcard_member.mbrdocuments')),
            ],
        ),
    ]
