# Generated by Django 5.2 on 2025-07-21 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0006_shareddocumentaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_fields', models.JSONField()),
                ('pin', models.CharField(max_length=10)),
                ('expiry_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobcard_member.mbrdocuments')),
            ],
        ),
        migrations.DeleteModel(
            name='SharedDocumentAccess',
        ),
    ]
