# Generated by Django 5.2.4 on 2025-07-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0007_educationlevel_specialization_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_id', models.CharField(max_length=50)),
                ('education_name', models.CharField(max_length=200)),
                ('education_description', models.TextField(blank=True, null=True)),
                ('specialization_id', models.CharField(max_length=100, unique=True)),
                ('specialization_name', models.CharField(max_length=200)),
                ('specialization_description', models.TextField(blank=True, null=True)),
                ('eligibility', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='education_level',
        ),
        migrations.DeleteModel(
            name='EducationLevel',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
