# Generated by Django 5.2 on 2025-08-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0007_documentaccess_delete_shareddocumentaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbrdocuments',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('verified', 'Verified')], default='pending', max_length=20),
        ),
    ]
