# Generated by Django 5.2.4 on 2025-07-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0007_documentaccess_delete_shareddocumentaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Member Card Number')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('happiness_rating', models.IntegerField()),
                ('has_issues', models.BooleanField()),
                ('issues_description', models.TextField(blank=True, null=True)),
                ('liked_most', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
