# Generated by Django 5.2.4 on 2025-07-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='happiness_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
