# Generated by Django 5.2 on 2025-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0008_mbrdocuments_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbrdocuments',
            name='status',
        ),
        migrations.AddField(
            model_name='mbrdocuments',
            name='document_status',
            field=models.JSONField(default=dict, help_text="Store status of each document individually, e.g., {'Resume': 'verified', 'TenthCertificate': 'pending'}"),
        ),
    ]
