# Generated by Django 5.2 on 2025-08-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0009_remove_mbrdocuments_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.BigIntegerField(verbose_name='Member Card Number')),
                ('requested_by', models.IntegerField(verbose_name='Business/HR ID')),
                ('documents', models.JSONField(default=dict, help_text="List of documents requested for verification with initial status, e.g., {'Resume': 'pending', 'TenthCertificate': 'pending'}")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
