# Generated by Django 5.2.4 on 2025-07-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0009_alter_feedback_happiness_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='has_issues',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
