# Generated by Django 5.2.4 on 2025-07-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0010_alter_feedback_has_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
