# Generated by Django 5.2 on 2025-08-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0010_documentverificationrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mbrdocuments',
            old_name='TwelfthCertificate',
            new_name='TwelthCertificate',
        ),
    ]
