# Generated by Django 5.2.4 on 2025-07-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_member', '0011_feedback_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='business_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
